import { ColorThemeId, ThemeConfig } from '../types';

export const COLOR_THEMES: Record<ColorThemeId, ThemeConfig> = {
  monochrome: {
    id: 'monochrome',
    name: 'Black & White Dark (VIP Pro)',
    nameHi: 'अल्ट्रा ब्लैक & व्हाइट डार्क (प्रो)',
    description: 'Sleek obsidian monochrome dark with crisp white typography, chrome borders & luxury gaming feel',
    descriptionHi: 'प्रीमियम ऑब्सिडियन ब्लैक, क्रिस्प वाइट टेक्स्ट और क्रोम फिनिश वीआईपी लुक',
    previewColors: ['#ffffff', '#27272a', '#a1a1aa', '#09090b'],
    bgClass: 'bg-[#050507]',
    headerBorder: 'border-white/15',
    ambientGlow1: 'bg-white/5',
    ambientGlow2: 'bg-zinc-600/10',
    activeTabClass: 'bg-white text-zinc-950 font-black shadow-lg shadow-white/15',
  },
  emerald: {
    id: 'emerald',
    name: 'Emerald Obsidian',
    nameHi: 'एमराल्ड ऑब्सिडियन (क्लासिक)',
    description: 'Deep midnight dark with rich neon emerald, royal violet & 24K gold',
    descriptionHi: 'गहरा मिडनाइट ब्लैक, लक्ज़री एमराल्ड ग्रीन और रॉयल गोल्ड',
    previewColors: ['#00e676', '#9333ea', '#ff1744', '#fbbf24'],
    bgClass: 'bg-[#080c14]',
    headerBorder: 'border-emerald-500/20',
    ambientGlow1: 'bg-emerald-500/15',
    ambientGlow2: 'bg-purple-600/10',
    activeTabClass: 'bg-gradient-to-r from-emerald-500 via-teal-500 to-emerald-600 text-slate-950 font-black shadow-lg shadow-emerald-500/30',
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Neon',
    nameHi: 'साइबर नियॉन (फ्यूचरिस्टिक)',
    description: 'Electric cyan, intense magenta violet & high-voltage neon glow',
    descriptionHi: 'इलेक्ट्रिक स्यान, वायलेट मैजेंटा और नियॉन ग्लो',
    previewColors: ['#06b6d4', '#d946ef', '#ec4899', '#3b82f6'],
    bgClass: 'bg-[#0b0816]',
    headerBorder: 'border-cyan-500/30',
    ambientGlow1: 'bg-cyan-500/15',
    ambientGlow2: 'bg-fuchsia-600/15',
    activeTabClass: 'bg-gradient-to-r from-cyan-500 via-fuchsia-500 to-indigo-600 text-white font-black shadow-lg shadow-cyan-500/30',
  },
  royalGold: {
    id: 'royalGold',
    name: 'Royal 24K Gold',
    nameHi: 'रॉयल 24K गोल्ड (वीआईपी)',
    description: 'Imperial luxury with champagne gold, sunburst amber & diamond black',
    descriptionHi: 'शाही 24 कैरेट गोल्ड, सनबर्स्ट एम्बर और वीआईपी ब्लैक',
    previewColors: ['#fbbf24', '#f59e0b', '#10b981', '#ef4444'],
    bgClass: 'bg-[#0c0a06]',
    headerBorder: 'border-amber-500/30',
    ambientGlow1: 'bg-amber-500/15',
    ambientGlow2: 'bg-emerald-500/10',
    activeTabClass: 'bg-gradient-to-r from-amber-400 via-yellow-500 to-amber-600 text-slate-950 font-black shadow-lg shadow-amber-500/30',
  },
  rubyMonaco: {
    id: 'rubyMonaco',
    name: 'Ruby Monaco',
    nameHi: 'रूबी मोनाको (कसीनो)',
    description: 'High roller Monte Carlo with intense ruby crimson, scarlet & gold',
    descriptionHi: 'मोंटे कार्लो रूबी क्रिम्सन, स्कारलेट और गोल्ड',
    previewColors: ['#f43f5e', '#e11d48', '#fbbf24', '#10b981'],
    bgClass: 'bg-[#12080a]',
    headerBorder: 'border-rose-500/30',
    ambientGlow1: 'bg-rose-500/15',
    ambientGlow2: 'bg-amber-500/10',
    activeTabClass: 'bg-gradient-to-r from-rose-500 via-red-500 to-rose-600 text-white font-black shadow-lg shadow-rose-500/30',
  },
};
